services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_DB: ragent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass "123456"
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata:
